// app/api/turbo-study/route.ts
import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const maxDuration = 60; 

const apiKey = process.env.GOOGLE_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey || "");

const MODELS = [
  "gemini-2.5-flash",
  "gemini-1.5-pro",
  "gemini-1.5-flash"
];

function cleanAndParseJSON(text: string) {
    let cleanText = text.replace(/```json\s*/g, '').replace(/```\s*/g, '');
    const firstOpen = cleanText.indexOf('[');
    const lastClose = cleanText.lastIndexOf(']');
    if (firstOpen !== -1 && lastClose !== -1 && lastClose > firstOpen) {
        cleanText = cleanText.substring(firstOpen, lastClose + 1);
    }
    return JSON.parse(cleanText);
}

function extractYoutubeId(url: string) {
    const regex = /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/i;
    const match = url.match(regex);
    return match ? match[1] : null;
}

// Extractor agresivo usando red de proxies (Piped API) para saltar bloqueos de Vercel/YouTube
async function getYouTubeTranscript(videoId: string) {
    // Lista de instancias públicas que actúan de puente
    const pipedInstances = [
        'https://pipedapi.kavin.rocks',
        'https://pipedapi.tokhmi.xyz',
        'https://api.piped.projectsegfau.lt'
    ];

    let subtitlesData = null;

    // Intentamos en cada servidor hasta que uno nos devuelva los datos
    for (const instance of pipedInstances) {
        try {
            console.log(`Intentando extraer de: ${instance}...`);
            const res = await fetch(`${instance}/streams/${videoId}`, {
                headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' }
            });
            
            if (!res.ok) continue;
            const data = await res.json();
            
            if (data.subtitles && data.subtitles.length > 0) {
                subtitlesData = data.subtitles;
                break;
            }
        } catch (e) {
            console.warn(`Falló la instancia ${instance}`);
            continue;
        }
    }

    if (!subtitlesData) {
        throw new Error("Extracción fallida: El vídeo realmente no tiene subtítulos o las redes proxy están temporalmente caídas.");
    }

    // Buscamos preferentemente español (no autogenerado primero, luego cualquiera), luego inglés, luego el primero disponible
    let selectedSub = subtitlesData.find((s: any) => s.code.startsWith('es') && !s.autoGenerated) ||
                      subtitlesData.find((s: any) => s.code.startsWith('es')) || 
                      subtitlesData.find((s: any) => s.code.startsWith('en')) || 
                      subtitlesData[0];

    try {
        // Descargamos el archivo real de subtítulos
        const subRes = await fetch(selectedSub.url);
        const rawText = await subRes.text();

        // Limpieza extrema de VTT/XML a texto plano para la IA
        const cleanText = rawText
            .replace(/WEBVTT[\s\S]*?(?=\d{2}:)/g, '') // Quita cabeceras VTT
            .replace(/\d{2}:\d{2}:\d{2}\.\d{3} --> \d{2}:\d{2}:\d{2}\.\d{3}.*\n/g, '') // Quita marcas de tiempo
            .replace(/<[^>]+>/g, ' ') // Quita tags HTML o XML
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>')
            .replace(/&#39;/g, "'")
            .replace(/&quot;/g, '"')
            .replace(/\n+/g, ' ') // Quita saltos de línea
            .replace(/\s{2,}/g, ' ') // Quita espacios dobles
            .trim();

        if (!cleanText || cleanText.length < 10) {
            throw new Error("Se descargó el archivo pero estaba vacío.");
        }

        return cleanText;
    } catch (error: any) {
        throw new Error(`Error al procesar el archivo de texto: ${error.message}`);
    }
}

export async function POST(request: Request) {
  if (!apiKey) {
    return NextResponse.json({ error: "Missing API Key" }, { status: 500 });
  }

  try {
    const body = await request.json();
    const { action, messages, pdfBase64, youtubeUrl, youtubeTranscript, questionCount, language } = body;
    
    // ==========================================
    // EXTRACCIÓN ÚNICA DE SUBTÍTULOS
    // ==========================================
    if (action === "fetch_youtube") {
        const videoId = extractYoutubeId(youtubeUrl);
        if (!videoId) return NextResponse.json({ error: "URL de YouTube inválida" }, { status: 400 });
        
        try {
            const transcript = await getYouTubeTranscript(videoId);
            return NextResponse.json({ data: transcript });
        } catch (error: any) {
            console.error("Transcript fetch error:", error);
            return NextResponse.json({ error: error.message }, { status: 400 });
        }
    }

    let systemInstruction = "You are an expert and friendly AI tutor. Your goal is to help the user study the provided material. Focus on explaining the main themes and core concepts. You may use your general knowledge to complement the explanations, but do not hallucinate information unrelated to the subjects of the document.";
    let promptText = messages?.[messages.length - 1]?.content || "";
    
    if (action === "generate_test") {
         systemInstruction = `You are an expert university professor creating a multiple-choice test. 
         Generate exactly ${questionCount} questions in ${language} about the MAIN TOPICS discussed in the provided material.
         
         CRITICAL RULES:
         1. DO NOT ask about specific anecdotes, trivial examples, or overly specific numbers/names mentioned in the text.
         2. Focus exclusively on the CORE CONCEPTS, theories, and the general framework of the document.
         3. You MUST use your extensive external knowledge to enrich the questions and provide deeper context, as long as it directly relates to the main subjects covered in the provided material.
         
         Return ONLY a raw JSON array. Exact format: [{"question": "...", "options": {"A": "...", "B": "...", "C": "...", "D": "..."}, "answer": "A", "explanation": "Brief explanation of why this is correct based on the concept"}]`;
         promptText = "Analyze the core themes of the provided material and generate the conceptual test now.";
    }

    const parts: any[] = [];
    
    if (pdfBase64) {
        parts.push({
            inlineData: { data: pdfBase64, mimeType: "application/pdf" }
        });
    }
    
    if (youtubeTranscript) {
        parts.push({ text: `Study Material (YouTube Video Transcript):\n\n${youtubeTranscript}\n\n---\nPlease use the main topics from the transcript above as the primary basis for your response.` });
    }
    
    if (action === 'chat' && messages && messages.length > 1) {
        const historyText = messages.slice(0, -1).map((msg: any) => 
            `${msg.role === 'user' ? 'Student' : 'AI Tutor'}: ${msg.content}`
        ).join('\n\n');
        parts.push({ text: `Conversation history:\n${historyText}\n\nNew student question:` });
    }

    parts.push({ text: promptText });

    let success = false;
    let resultData;
    let lastError: any;

    for (const modelName of MODELS) {
        try {
            console.log(`[TurboStudy] Attempting '${action}' with model: ${modelName}`);
            
            const isGemini = modelName.includes("gemini");
            const generationConfig = (action === "generate_test" && isGemini)
                ? { responseMimeType: "application/json" } 
                : undefined;

            const model = genAI.getGenerativeModel({
                model: modelName,
                generationConfig,
                systemInstruction: isGemini ? systemInstruction : undefined,
            });
            
            let finalParts = [...parts];
            if (!isGemini) {
                finalParts = [{ text: `System instructions: ${systemInstruction}\n\n` }, ...parts];
            }

            const result = await model.generateContent({
                contents: [{ role: "user", parts: finalParts }]
            });
            
            const textResponse = result.response.text();

            if (action === "generate_test") {
                resultData = cleanAndParseJSON(textResponse);
                if (!Array.isArray(resultData)) throw new Error("Invalid JSON structure");
            } else {
                resultData = textResponse;
            }

            success = true;
            break;
        } catch (aiError: any) {
            console.warn(`Failed with ${modelName}:`, aiError.message);
            lastError = aiError;
        }
    }

    if (!success) {
        return NextResponse.json({ error: `Failed after trying all AI models. Last error: ${lastError?.message}` }, { status: 500 });
    }

    return NextResponse.json({ data: resultData });

  } catch (error: any) {
    console.error("Error in turbo-study:", error);
    return NextResponse.json({ error: error.message || "Server error" }, { status: 500 });
  }
}